/** Deterministic cents-based scenarios. No credit approval or bank transaction execution. */
export const snapshot={asOf:'2026-10-06',business:'Maison & Maple',owner:'Maya',available:2450000,cushion:1000000,expectedIncome:1200000,
 commitments:[{id:'rent',label:'Boutique rent',date:'2026-10-10',cents:320000},{id:'supplier',label:'Supplier invoice',date:'2026-10-15',cents:180000},{id:'payroll',label:'Payroll',date:'2026-10-16',cents:240000},{id:'insurance',label:'Business insurance',date:'2026-10-20',cents:40000},{id:'reserve',label:'Planned tax reserve',date:'2026-10-28',cents:100000},{id:'later',label:'November supplier invoice',date:'2026-11-15',cents:150000}],
 activity:[{date:'Oct 05',name:'Customer sales',category:'Sales',cents:485000},{date:'Oct 04',name:'Northline Furniture Co.',category:'Inventory',cents:-235000},{date:'Oct 03',name:'Studio freight',category:'Delivery',cents:-48000},{date:'Oct 02',name:'Customer sales',category:'Sales',cents:362000}],
 expansion:{inventory:3500000,equipment:1200000,improvements:1500000,moving:500000,cashCushion:1000000,ownerContribution:1500000,documents:[{id:'pnl',label:'Current profit & loss statement',complete:true},{id:'statements',label:'Recent business bank statements',complete:true},{id:'debt',label:'Existing debt schedule',complete:false},{id:'lease',label:'Proposed lease and space costs',complete:false},{id:'quotes',label:'Inventory and equipment quotes',complete:true},{id:'forecast',label:'Expansion cash-flow forecast',complete:false}]}};
export function cents(value){const s=String(value).trim().replace(/^\$/,'').replaceAll(',','');if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('Enter a positive dollar amount with at most two decimals.');const [whole,fraction='']=s.split('.');const result=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(result)||result>100000000000)throw Error('Amount must be at most $1 billion.');return result;}
export function windowEnd(asOf){const date=new Date(asOf+'T00:00:00Z');date.setUTCDate(date.getUTCDate()+30);return date.toISOString().slice(0,10);}
export function upcoming(state){const end=windowEnd(state.asOf);return state.commitments.filter(c=>c.date>=state.asOf&&c.date<end);}
export function evaluatePurchase(state,purchase,{includeIncome=false,commitmentsComplete=true}={}){for(const n of[state.available,state.cushion,purchase,state.expectedIncome,...state.commitments.map(c=>c.cents)])if(!Number.isSafeInteger(n)||n<0)throw Error('Amounts must be nonnegative integer cents.');const commitments=upcoming(state).reduce((sum,c)=>sum+c.cents,0),income=includeIncome?state.expectedIncome:0,remaining=state.available-purchase-commitments+income,gap=remaining-state.cushion;return {status:!commitmentsComplete?'incomplete':gap<0?'below':'above',purchase,available:state.available,commitments,income,remaining,cushion:state.cushion,gap,maxPurchase:Math.max(0,state.available-commitments-state.cushion),asOf:state.asOf,endExclusive:windowEnd(state.asOf),scenario:includeIncome?'expected-income':'cash-only',assumptions:['Available cash is already net of bank holds.','Commitments are future items not deducted from available cash.','Expected income is uncertain and excluded unless selected.','No additional obligations or transaction fees are modeled.']};}
export function expansionSummary(plan){const costKeys=['inventory','equipment','improvements','moving','cashCushion'];for(const key of[...costKeys,'ownerContribution'])if(!Number.isSafeInteger(plan[key])||plan[key]<0)throw Error('Project amounts must be nonnegative cents.');const total=costKeys.reduce((sum,key)=>sum+plan[key],0);return {total,gap:Math.max(0,total-plan.ownerContribution),excessContribution:Math.max(0,plan.ownerContribution-total),complete:plan.documents.filter(d=>d.complete).length,documentCount:plan.documents.length};}
export function loanPayment(principal,annualPercent,months){if(!Number.isSafeInteger(principal)||principal<0||!Number.isFinite(annualPercent)||annualPercent<0||annualPercent>100||!Number.isInteger(months)||months<1||months>360)throw Error('Check financing amount, rate and term.');const rate=annualPercent/1200;return Math.round(rate===0?principal/months:principal*rate/(1-Math.pow(1+rate,-months)));}
export function parseIntent(message){const text=String(message).trim();if(!text||text.length>500)return {kind:'invalid'};if(/\b(buy|purchase|spend|afford|inventory)\b/i.test(text)){const tokens=[...text.matchAll(/-?\s*\$?\s*(\d[\d,]*(?:\.\d+)?)(\s*k\b)?/gi)];if(tokens.length!==1||/-\s*\$?\s*\d/.test(text))return {kind:'purchase',needsAmount:true};const token=tokens[0];try{let amount=cents(token[1]);if(token[2])amount*=1000;if(!Number.isSafeInteger(amount)||amount>100000000000)return {kind:'invalid'};return {kind:'purchase',amount};}catch{return {kind:'invalid'};}}if(/\b(warehouse|expand|expansion|funding|lending|loan|ready|documents)\b/i.test(text))return {kind:'expansion'};if(/\b(credit|score)\b/i.test(text))return {kind:'credit'};if(/\b(tax|write.?off|deduct)\b/i.test(text))return {kind:'tax'};if(/\b(cash|balance|account|money|today)\b/i.test(text))return {kind:'cash'};return {kind:'unsupported'};}
